
# Site settings
title: Yaquan Chang
name: Yaquan Chang
subtitle: MSc canadidate at nature management
email: yaquanchang0623@outlook.com
description: >
  MSc canadidate
baseurl: ""
url: "https://yaquan.github.io/"
github_username:  YaquanChang
disqus_baseurl: "https://yaquan.github.io/"
disqus_shortname: https-yaquan-github-io
permalink: :title

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Yaquan"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: YaquanChang
    url: https://github.com/YaquanChang
    desc: Fork me on GitHub
    share: false


