
# Site settings
title: Yaquan Chang
name: Yaquan Chang
subtitle: MSc in nature management
email: yaquanchang0623@outlook.com
description: >
  MSc 
baseurl: ""
url: "https://yaquanchang.github.io/"
github_username:  YaquanChang
disqus_baseurl: "https://yaquanchang.github.io/"
disqus_shortname: https-yaquanchang-github-io
permalink: :title

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Yaquan Chang"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: Twitter
    icon: twitter
    username: YaquanChang
    url: https://twitter.com/YaquanChang/
    desc: Follow me on Twitter
    share: false


